### ISSUE TITLE
bigwig is not supported as advertised?

### ISSUE THREAD

**Issue by clouds-drift** [JetBrains-Research/span#20]

**Comment by olegs** [comment]
The short answer is NO, not anymore. 
SPAN is not published yet and is under heavy development at the moment. Some time ago there was an option to use bigWig as input format, however underlying statistical model adds some limitations on the method how bigWig should be produced, i.e. redundant reads should be filtered out, which is not true for most of the bigWig files available. So that we restricted treatment and support format to reads only (BAM or BED.GZ). 
Thanks you for the issue, we will remove out-of-date mentioning of bigWig as supported input format at https://research.jetbrains.org/groups/biolabs/tools/span-peak-analyzer.

**Comment by clouds-drift** [comment]
Thanks for your answer. 
But I really expect it's possible to support bigwig format, because it's so convenient.  Hope it could be possible after SPAN is published.
Probably, limit the maximum of coverage may  recuse some bw files with high duplicates.
Best

**Comment by olegs** [comment]
Thanks, will consider it in the future!
